DROP TABLE entrenamiento;
DROP TABLE usuario;
drop procedure MODIFICAR_ENTRENAMIENTO;
drop procedure Modificar_usuario;
drop trigger AUDITORIA_ENTRENO_DEPORTISTA;
drop trigger AUDITORIA_MAX_ENTRENO;
drop trigger NOM_APE_VOCALES;
drop sequence SEQUENCE_ENTRENAMIENTO;
drop sequence SEQUENCE_USUARIO;